import { allArticles, type Article } from "contentlayer/generated";
import { compareDesc } from "date-fns";
import { tagToSlug } from "./utils";

/** All published articles, newest first. Drafts (published: false) are excluded. */
export function getAllArticles(): Article[] {
  return allArticles
    .filter((a) => a.published !== false)
    .sort((a, b) => compareDesc(new Date(a.date), new Date(b.date)));
}

/** Look up a single published article by its slug. */
export function getArticleBySlug(slug: string): Article | undefined {
  return getAllArticles().find((a) => a.slug === slug);
}

/** Articles that share the given tag slug. */
export function getArticlesByTag(tagSlug: string): Article[] {
  return getAllArticles().filter((a) =>
    a.tags.some((t) => tagToSlug(t) === tagSlug)
  );
}

/**
 * Search published articles by keyword(s).
 *
 * Splits the query into terms and requires every term to appear somewhere in
 * the article (AND semantics), then ranks by where the matches land — title
 * hits count most, body hits least. Case-insensitive.
 */
export function searchArticles(query: string): Article[] {
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .map((t) => t.trim())
    .filter(Boolean);

  if (terms.length === 0) return [];

  const scored = getAllArticles().map((article) => {
    const fields = {
      title: article.title.toLowerCase(),
      tags: article.tags.join(" ").toLowerCase(),
      series: (article.series ?? "").toLowerCase(),
      description: article.description.toLowerCase(),
      body: article.body.raw.toLowerCase(),
    };
    const combined = Object.values(fields).join(" ");

    // Every term must appear somewhere for the article to be a match.
    if (!terms.every((term) => combined.includes(term))) {
      return { article, score: 0 };
    }

    let score = 0;
    for (const term of terms) {
      if (fields.title.includes(term)) score += 10;
      if (fields.tags.includes(term)) score += 5;
      if (fields.series.includes(term)) score += 4;
      if (fields.description.includes(term)) score += 3;
      if (fields.body.includes(term)) score += 1;
    }
    return { article, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((s) => s.article);
}

/** Unique tags across all published articles with their post counts. */
export function getAllTags(): { tag: string; slug: string; count: number }[] {
  const counts = new Map<string, { tag: string; count: number }>();
  for (const article of getAllArticles()) {
    for (const tag of article.tags) {
      const slug = tagToSlug(tag);
      const existing = counts.get(slug);
      if (existing) {
        existing.count += 1;
      } else {
        counts.set(slug, { tag, count: 1 });
      }
    }
  }
  return Array.from(counts.entries())
    .map(([slug, { tag, count }]) => ({ tag, slug, count }))
    .sort((a, b) => b.count - a.count);
}

/**
 * Related articles: prefer same series, then most shared tags.
 * Falls back to most recent articles when there are no overlaps.
 */
export function getRelatedArticles(current: Article, limit = 3): Article[] {
  const others = getAllArticles().filter((a) => a.slug !== current.slug);
  const currentTags = new Set(current.tags.map(tagToSlug));

  const scored = others.map((a) => {
    let score = 0;
    if (current.series && a.series === current.series) score += 5;
    score += a.tags.filter((t) => currentTags.has(tagToSlug(t))).length;
    return { article: a, score };
  });

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.article);
}

export type TocItem = {
  id: string;
  text: string;
  level: 2 | 3;
};

/**
 * Extract H2/H3 headings from raw MDX for the table of contents.
 * IDs match those generated by rehype-slug (github-slugger style).
 */
export function extractToc(raw: string): TocItem[] {
  const items: TocItem[] = [];
  const seen = new Map<string, number>();

  // Only match headings outside fenced code blocks.
  const withoutCode = raw.replace(/```[\s\S]*?```/g, "");
  const lines = withoutCode.split("\n");

  for (const line of lines) {
    const match = /^(#{2,3})\s+(.*)$/.exec(line.trim());
    if (!match) continue;

    const level = match[1].length as 2 | 3;
    const text = match[2].replace(/[#*`_]/g, "").trim();

    let id = text
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/\s+/g, "-");

    // github-slugger dedupes repeated slugs with -1, -2, ...
    if (seen.has(id)) {
      const next = (seen.get(id) as number) + 1;
      seen.set(id, next);
      id = `${id}-${next}`;
    } else {
      seen.set(id, 0);
    }

    items.push({ id, text, level });
  }

  return items;
}
