"use client";

import { useEffect, useState } from "react";

const readImage = (file: File) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); const url = URL.createObjectURL(file); image.onload = () => { URL.revokeObjectURL(url); resolve(image); }; image.onerror = reject; image.src = url; });

export default function ImageResizer() {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const [ratio, setRatio] = useState(1); const [locked, setLocked] = useState(true); const [quality, setQuality] = useState(90); const [format, setFormat] = useState<"image/jpeg" | "image/png" | "image/webp">("image/jpeg"); const [output, setOutput] = useState<string | null>(null);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); if (output) URL.revokeObjectURL(output); }, [preview, output]);
  async function select(file?: File) { if (!file || !file.type.startsWith("image/")) return; if (preview) URL.revokeObjectURL(preview); if (output) URL.revokeObjectURL(output); const image = await readImage(file); setFile(file); setPreview(URL.createObjectURL(file)); setWidth(image.naturalWidth); setHeight(image.naturalHeight); setRatio(image.naturalWidth / image.naturalHeight); setOutput(null); }
  function changeWidth(value: number) { setWidth(value); if (locked) setHeight(Math.max(1, Math.round(value / ratio))); }
  function changeHeight(value: number) { setHeight(value); if (locked) setWidth(Math.max(1, Math.round(value * ratio))); }
  async function resize() { if (!file || !width || !height) return; const image = await readImage(file); const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const context = canvas.getContext("2d"); if (!context) return; if (format === "image/jpeg") { context.fillStyle = "#ffffff"; context.fillRect(0, 0, width, height); } context.drawImage(image, 0, 0, width, height); canvas.toBlob((blob) => { if (!blob) return; if (output) URL.revokeObjectURL(output); setOutput(URL.createObjectURL(blob)); }, format, quality / 100); }
  const extension = format === "image/jpeg" ? "jpg" : format === "image/png" ? "png" : "webp";
  return <div className="card bg-card border-custom rounded-4"><div className="card-body p-4"><label htmlFor="resize-image" className="h6 fw-bold d-block mb-2">Choose an image</label><input id="resize-image" className="form-control bg-card border-custom text-body" type="file" accept="image/*" onChange={(e) => select(e.target.files?.[0])} />{file && <><div className="row g-3 mt-2"><div className="col-sm-5"><label className="form-label small" htmlFor="image-width">Width (px)</label><input id="image-width" className="form-control bg-card border-custom text-body" type="number" min="1" value={width} onChange={(e) => changeWidth(Number(e.target.value))} /></div><div className="col-sm-5"><label className="form-label small" htmlFor="image-height">Height (px)</label><input id="image-height" className="form-control bg-card border-custom text-body" type="number" min="1" value={height} onChange={(e) => changeHeight(Number(e.target.value))} /></div><div className="col-sm-2 d-flex align-items-end"><button type="button" className={`btn w-100 ${locked ? "btn-primary" : "btn-outline-light"}`} onClick={() => setLocked(!locked)} aria-label="Toggle aspect ratio"><i className={`bi ${locked ? "bi-lock-fill" : "bi-unlock"}`} /></button></div><div className="col-sm-6"><label className="form-label small" htmlFor="image-format">Format</label><select id="image-format" className="form-select bg-card border-custom text-body" value={format} onChange={(e) => setFormat(e.target.value as typeof format)}><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div><div className="col-sm-6"><label className="form-label small" htmlFor="image-quality">Quality: {quality}%</label><input id="image-quality" className="form-range" type="range" min="10" max="100" value={quality} disabled={format === "image/png"} onChange={(e) => setQuality(Number(e.target.value))} /></div></div><p className="small text-secondary-custom mt-3 mb-0">{locked ? "Aspect ratio is locked." : "Aspect ratio is unlocked."} PNG is lossless; JPEG and WebP use the quality setting.</p><div className="d-flex flex-wrap gap-2 mt-4"><button type="button" className="btn btn-primary" onClick={resize}><i className="bi bi-aspect-ratio me-2" />Resize image</button>{output && <a className="btn btn-outline-light" href={output} download={`${file.name.replace(/\.[^.]+$/, "")}-${width}x${height}.${extension}`}><i className="bi bi-download me-2" />Download {width} × {height}</a>}</div>{preview && <img src={output ?? preview} alt="Image preview" className="img-fluid rounded-3 border border-custom mt-4" style={{ maxHeight: "360px" }} />}</>}</div></div>;
}
